// flow-typed signature: 2056a17a36365d22ad5f6bf17c8e2408
// flow-typed version: <<STUB>>/loader-utils_v^1.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loader-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loader-utils' {
  declare module.exports: {
    getOptions(obj: any): { [string]: any } | null;
  };
}
