// flow-typed signature: 31811c9483e4a0ffb6d44c257c6c64d1
// flow-typed version: <<STUB>>/properties_v^1.2.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'properties' {
  declare module.exports: {
    parse(source: string): { [string]: string } | void;
  };
}
