// flow-typed signature: 31811c9483e4a0ffb6d44c257c6c64d1
// flow-typed version: <<STUB>>/properties_v^1.2.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'properties/lib/escape' {
  declare module.exports: any;
}

declare module 'properties/lib/index' {
  declare module.exports: any;
}

declare module 'properties/lib/parse' {
  declare module.exports: any;
}

declare module 'properties/lib/read' {
  declare module.exports: any;
}

declare module 'properties/lib/stringifier' {
  declare module.exports: any;
}

declare module 'properties/lib/stringify' {
  declare module.exports: any;
}

declare module 'properties/lib/write' {
  declare module.exports: any;
}

// Filename aliases
declare module 'properties/lib/escape.js' {
  declare module.exports: $Exports<'properties/lib/escape'>;
}
declare module 'properties/lib/index.js' {
  declare module.exports: $Exports<'properties/lib/index'>;
}
declare module 'properties/lib/parse.js' {
  declare module.exports: $Exports<'properties/lib/parse'>;
}
declare module 'properties/lib/read.js' {
  declare module.exports: $Exports<'properties/lib/read'>;
}
declare module 'properties/lib/stringifier.js' {
  declare module.exports: $Exports<'properties/lib/stringifier'>;
}
declare module 'properties/lib/stringify.js' {
  declare module.exports: $Exports<'properties/lib/stringify'>;
}
declare module 'properties/lib/write.js' {
  declare module.exports: $Exports<'properties/lib/write'>;
}
